import type { Subscriber } from "./types"

export const mockSubscribers: Subscriber[] = [
  {
    id: "1",
    email: "lionel@musicalbasics.com",
    firstName: "Lionel",
    lastName: "Yu",
    tags: ["Admin", "Piano"],
    status: "Active",
    addedAt: "2024-12-12",
    notes: "Founder and admin. Prefers communication via email.",
  },
  {
    id: "2",
    email: "student@example.com",
    firstName: "Alice",
    lastName: "Johnson",
    tags: ["Student", "Theory"],
    status: "Active",
    addedAt: "2024-11-28",
    notes: "Enrolled in music theory course. Very engaged student.",
  },
  {
    id: "3",
    email: "olduser@test.com",
    firstName: "Bob",
    lastName: "Smith",
    tags: [],
    status: "Bounced",
    addedAt: "2024-10-15",
    notes: "Email bounced multiple times. Need to verify address.",
  },
  {
    id: "4",
    email: "vip.member@music.com",
    firstName: "Sarah",
    lastName: "Williams",
    tags: ["VIP", "Piano", "Theory"],
    status: "Active",
    addedAt: "2024-09-20",
    notes: "Long-time VIP member. Completed multiple courses.",
  },
  {
    id: "5",
    email: "inactive@user.com",
    firstName: "Mike",
    lastName: "Brown",
    tags: ["Student"],
    status: "Unsubscribed",
    addedAt: "2024-08-05",
    notes: "Unsubscribed due to moving abroad.",
  },
  {
    id: "6",
    email: "beginner@piano.com",
    firstName: "Emma",
    lastName: "Davis",
    tags: ["Beginner", "Piano"],
    status: "Active",
    addedAt: "2024-12-01",
    notes: "Just started piano lessons. Very enthusiastic!",
  },
  {
    id: "7",
    email: "pro@musician.net",
    firstName: "David",
    lastName: "Lee",
    tags: ["VIP", "Advanced"],
    status: "Active",
    addedAt: "2024-07-18",
    notes: "Professional musician. Interested in advanced courses.",
  },
]

export const allTags = ["Admin", "Piano", "Student", "Theory", "VIP", "Beginner", "Advanced"]
